// fuse_time_brazil.h #ifndef FUSE_TIME_BRAZIL_H #define FUSE_TIME_BRAZIL_H

#define FUSE_TIME_BRAZIL_FERNANDO_DE_NORONHA   "-02:00" #define FUSE_TIME_BRAZIL_BRASILIA              "-03:00" #define FUSE_TIME_BRAZIL_SAO_PAULO             "-03:00" #define FUSE_TIME_BRAZIL_RIO_DE_JANEIRO        "-03:00" #define FUSE_TIME_BRAZIL_MINAS_GERAIS          "-03:00" #define FUSE_TIME_BRAZIL_BAHIA                 "-03:00" #define FUSE_TIME_BRAZIL_CEARA                 "-03:00" #define FUSE_TIME_BRAZIL_PERNAMBUCO            "-03:00" #define FUSE_TIME_BRAZIL_RIO_GRANDE_DO_SUL     "-03:00" #define FUSE_TIME_BRAZIL_PARANA                "-03:00" #define FUSE_TIME_BRAZIL_SANTA_CATARINA        "-03:00" #define FUSE_TIME_BRAZIL_GOIAS                 "-03:00" #define FUSE_TIME_BRAZIL_DISTRITO_FEDERAL      "-03:00" #define FUSE_TIME_BRAZIL_MARANHAO              "-03:00" #define FUSE_TIME_BRAZIL_PARAIBA               "-03:00" #define FUSE_TIME_BRAZIL_SERGIPE               "-03:00" #define FUSE_TIME_BRAZIL_PIAUI                 "-03:00" #define FUSE_TIME_BRAZIL_RIO_GRANDE_DO_NORTE   "-03:00" #define FUSE_TIME_BRAZIL_ESPIRITO_SANTO        "-03:00" #define FUSE_TIME_BRAZIL_PARA                  "-03:00" #define FUSE_TIME_BRAZIL_AMAPA                 "-03:00" #define FUSE_TIME_BRAZIL_TOCANTINS             "-03:00"

#define FUSE_TIME_BRAZIL_MATO_GROSSO           "-04:00" #define FUSE_TIME_BRAZIL_MATO_GROSSO_DO_SUL    "-04:00" #define FUSE_TIME_BRAZIL_RONDONIA              "-04:00" #define FUSE_TIME_BRAZIL_RORAIMA               "-04:00" #define FUSE_TIME_BRAZIL_AMAZONAS              "-04:00"

#define FUSE_TIME_BRAZIL_ACRE                  "-05:00"

extern const char *fuse_time_brazil_list[]; extern const int fuse_time_brazil_count;

#endif

// fuse_time_brazil.c #include "fuse_time_brazil.h"

const char *fuse_time_brazil_list[] = { FUSE_TIME_BRAZIL_FERNANDO_DE_NORONHA, FUSE_TIME_BRAZIL_BRASILIA, FUSE_TIME_BRAZIL_SAO_PAULO, FUSE_TIME_BRAZIL_RIO_DE_JANEIRO, FUSE_TIME_BRAZIL_MINAS_GERAIS, FUSE_TIME_BRAZIL_BAHIA, FUSE_TIME_BRAZIL_CEARA, FUSE_TIME_BRAZIL_PERNAMBUCO, FUSE_TIME_BRAZIL_RIO_GRANDE_DO_SUL, FUSE_TIME_BRAZIL_PARANA, FUSE_TIME_BRAZIL_SANTA_CATARINA, FUSE_TIME_BRAZIL_GOIAS, FUSE_TIME_BRAZIL_DISTRITO_FEDERAL, FUSE_TIME_BRAZIL_MARANHAO, FUSE_TIME_BRAZIL_PARAIBA, FUSE_TIME_BRAZIL_SERGIPE, FUSE_TIME_BRAZIL_PIAUI, FUSE_TIME_BRAZIL_RIO_GRANDE_DO_NORTE, FUSE_TIME_BRAZIL_ESPIRITO_SANTO, FUSE_TIME_BRAZIL_PARA, FUSE_TIME_BRAZIL_AMAPA, FUSE_TIME_BRAZIL_TOCANTINS, FUSE_TIME_BRAZIL_MATO_GROSSO, FUSE_TIME_BRAZIL_MATO_GROSSO_DO_SUL, FUSE_TIME_BRAZIL_RONDONIA, FUSE_TIME_BRAZIL_RORAIMA, FUSE_TIME_BRAZIL_AMAZONAS, FUSE_TIME_BRAZIL_ACRE };

const int fuse_time_brazil_count = sizeof(fuse_time_brazil_list) / sizeof(fuse_time_brazil_list[0]);
